-- Create the employee_category_percentages table
CREATE TABLE employee_gl_allocation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID NOT NULL,
  billing_account_id UUID NOT NULL,
  percentage DECIMAL(5,2) NOT NULL CHECK (percentage >= 0 AND percentage <= 100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add foreign key constraints
ALTER TABLE employee_gl_allocation 
ADD CONSTRAINT fk_employee
FOREIGN KEY (employee_id)
REFERENCES employee(id)
ON DELETE CASCADE;

ALTER TABLE employee_gl_allocation 
ADD CONSTRAINT fk_billing_account
FOREIGN KEY (billing_account_id )
REFERENCES billing_account(id)
ON DELETE CASCADE;

-- Add a unique constraint to ensure one percentage per employee-category combination
ALTER TABLE employee_gl_allocation 
ADD CONSTRAINT unique_employee_category
UNIQUE (employee_id, billing_account_id);

