DROP TABLE IF EXISTS BillingJob;
DROP TABLE IF EXISTS BillingCategory;
DROP TABLE IF EXISTS BillingAccount;


CREATE TABLE BillingAccount (
    Id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    GlCode VARCHAR(10),
    Name VARCHAR(255),
    IsBilledBack BOOLEAN
);

CREATE TABLE BillingJob (
    Id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    EmployeeId UUID REFERENCES Employee(Id),
    EntityId UUID REFERENCES Entity(Id),
    PropertyId UUID REFERENCES Property(Id),
    BillingAccountId UUID REFERENCES BillingAccount(Id),
    BillingPeriodId UUID REFERENCES BillingPeriod(Id),
    Date DATE,
    StartTime TIMESTAMP,
    EndTime TIMESTAMP,
    BilledMiles DECIMAL(10, 2),
    MilageRate DECIMAL(10, 2),
    MilageTotal DECIMAL(10, 2),
    BilledHours DECIMAL(10, 2),
    HourlyRate DECIMAL(10, 2),
    HourlyToal DECIMAL(10, 2),
    Total DECIMAL(10, 2)
);

INSERT INTO Entity (Name) VALUES
('Situs GJ Multifamily'),
('Situs GJ Industrial LLC'),
('Situs GJ SFH'),
('Situs CFC One LLC'),
('Situs Pomona LLC'),
('Admin'),
('Situs Headwaters Lincoln LLC'),
('Situs Headwaters Courtyard LLC');


INSERT INTO Property (Name, Address, EntityId)
VALUES
('1009 Colorado Ave', '1009 Colorado Ave', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('1133 N. 18th Street', '1133 N. 18th Street', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Industrial LLC')),
('1240 -1254 Elm Ave', '1240 -1254 Elm Ave', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('1240 Bunting Ave', '1240 Bunting Ave', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('1511 N. 15th St.', '1511 N. 15th St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2003 Stan Dr.', '2003 Stan Dr.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2009 Industrial', '2009 Industrial', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Industrial LLC')),
('2011 Industrial', '2011 Industrial', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Industrial LLC')),
('2206 N. 22nd St.', '2206 N. 22nd St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('237 S. Elm St. #A', '237 S. Elm St. #A', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('237 S. Elm St. #B', '237 S. Elm St. #B', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('239 S. Elm St. #1', '239 S. Elm St. #1', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('239 S. Elm St. #2', '239 S. Elm St. #2', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('262 Nashua Ln.', '262 Nashua Ln.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2778 Monroe Ct.', '2778 Monroe Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2786 Quincy Pl.', '2786 Quincy Pl.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2825 Oxford Ave. B', '2825 Oxford Ave. B', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2836 Morningside Ct.', '2836 Morningside Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2837 1/2 Morningside Ct.', '2837 1/2 Morningside Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2837 Morningside Ct.', '2837 Morningside Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2839 1/2 Morningside Ct.', '2839 1/2 Morningside Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2839 Morningside Ct.', '2839 Morningside Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2841 Morningside Ct.', '2841 Morningside Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2842 Morningside Ct.', '2842 Morningside Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2843 Oxford Ave. B', '2843 Oxford Ave. B', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2844 Morningside A', '2844 Morningside A', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2844 Morningside B', '2844 Morningside B', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2844 Morningside C', '2844 Morningside C', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2931 N. View Dr. #2', '2931 N. View Dr. #2', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('2931 N. View Dr. #3', '2931 N. View Dr. #3', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('2931 N. View Dr. #4', '2931 N. View Dr. #4', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
-- Continuing from the previous insert statements
('2976 Emerald Cir.', '2976 Emerald Cir.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2976 Krista St.', '2976 Krista St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2978 Emerald Cir.', '2978 Emerald Cir.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2978 Krista St.', '2978 Krista St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2980 Emerald Cir.', '2980 Emerald Cir.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2980 Krista St.', '2980 Krista St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2982 Emerald Cir.', '2982 Emerald Cir.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2984 Emerald Cir.', '2984 Emerald Cir.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2984 Krista St.', '2984 Krista St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2985 Emerald Cir.', '2985 Emerald Cir.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2986 Krista St.', '2986 Krista St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2988 Krista St.', '2988 Krista St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('2990 Krista St.', '2990 Krista St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3129 Perkins Dr.', '3129 Perkins Dr.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3131 Perkins Dr.', '3131 Perkins Dr.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3135 Perkins Dr. #A', '3135 Perkins Dr. #A', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3135 Perkins Dr. #B', '3135 Perkins Dr. #B', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3137 Perkins Dr. #A', '3137 Perkins Dr. #A', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3137 Perkins Dr. #B', '3137 Perkins Dr. #B', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3138 Perkins Dr.', '3138 Perkins Dr.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3218 1/2 Kennedy Ave.', '3218 1/2 Kennedy Ave.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3225 Mesa Ave.', '3225 Mesa Ave.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('3228 Rood Ave', '3228 Rood Ave', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('445 30 Rd.', '445 30 Rd.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('451 Cottonwood Lk 1', '451 Cottonwood Lk 1', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('451 Cottonwood Lk 2', '451 Cottonwood Lk 2', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('460 32 1/8 Rd.', '460 32 1/8 Rd.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('469 Royal Ann Way', '469 Royal Ann Way', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('484 Tracy Dr.', '484 Tracy Dr.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('486 32 1/8 Rd.', '486 32 1/8 Rd.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('486 Tracy Dr.', '486 Tracy Dr.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('487 Tracy Dr', '487 Tracy Dr', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('518 1/2 Garland St.', '518 1/2 Garland St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('519 1/2 Garland St.', '519 1/2 Garland St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('523 1/2 Garland St.', '523 1/2 Garland St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('527 1/2 Garland St.', '527 1/2 Garland St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('527 Mandarin Ct.', '527 Mandarin Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('527 Mock Orange Ct.', '527 Mock Orange Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('528 Garland St.', '528 Garland St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('529 Mock Orange Ct.', '529 Mock Orange Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('532 Mock Orange Ct.', '532 Mock Orange Ct.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('533 Apricot Ln.', '533 Apricot Ln.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('557 Garfield Dr.', '557 Garfield Dr.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('566 Placer St.', '566 Placer St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('568 Placer St.', '568 Placer St.', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('630 S 7th Street', '630 S 7th Street', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Industrial LLC')),
('632 Hill', '632 Hill', (SELECT Id FROM Entity WHERE Name = 'Situs GJ Multifamily')),
('932 A Street', '932 A Street', (SELECT Id FROM Entity WHERE Name = 'Situs GJ SFH')),
('1000 Wellington', '1000 Wellington', (SELECT Id FROM Entity WHERE Name = 'Situs CFC One LLC')),
('Pomona Park', 'Pomona Park', (SELECT Id FROM Entity WHERE Name = 'Situs Pomona LLC')),
('Admin', 'Admin', (SELECT Id FROM Entity WHERE Name = 'Admin')),
('Lincoln Apartments', 'Lincoln Apartments', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('Courtyard Apartments', 'Courtyard Apartments', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('1303 Bunting #1', '1303 Bunting #1', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1303 Bunting #2', '1303 Bunting #2', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1303 Bunting #3', '1303 Bunting #3', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1303 Bunting #4', '1303 Bunting #4', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1456 Bunting #1', '1456 Bunting #1', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1456 Bunting #2', '1456 Bunting #2', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1456 Bunting #3', '1456 Bunting #3', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1456 Bunting #4', '1456 Bunting #4', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1460 Bunting #1', '1460 Bunting #1', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1460 Bunting #2', '1460 Bunting #2', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1460 Bunting #3', '1460 Bunting #3', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('1460 Bunting #4', '1460 Bunting #4', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Lincoln LLC')),
('2910 Bunting #1', '2910 Bunting #1', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #2', '2910 Bunting #2', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
-- Continuation of inserts for 2910 Bunting addresses
('2910 Bunting #3', '2910 Bunting #3', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #4', '2910 Bunting #4', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #5', '2910 Bunting #5', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #6', '2910 Bunting #6', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #7', '2910 Bunting #7', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #8', '2910 Bunting #8', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #9', '2910 Bunting #9', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #10', '2910 Bunting #10', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #11', '2910 Bunting #11', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #12', '2910 Bunting #12', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #13', '2910 Bunting #13', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #14', '2910 Bunting #14', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #15', '2910 Bunting #15', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #16', '2910 Bunting #16', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #17', '2910 Bunting #17', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #18', '2910 Bunting #18', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #19', '2910 Bunting #19', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #20', '2910 Bunting #20', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #21', '2910 Bunting #21', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #22', '2910 Bunting #22', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #23', '2910 Bunting #23', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #24', '2910 Bunting #24', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #25', '2910 Bunting #25', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #26', '2910 Bunting #26', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC')),
('2910 Bunting #27', '2910 Bunting #27', (SELECT Id FROM Entity WHERE Name = 'Situs Headwaters Courtyard LLC'));


INSERT INTO BillingAccount (GlCode, Name, IsBilledBack)
VALUES
('6102', 'Accounting', FALSE),
('6111', 'Management', FALSE),
('6112', 'Leasing', FALSE),
('6113', 'Marketing', FALSE),
('6114', 'Payroll', FALSE),
('6115', 'Admin', TRUE),
('6141', 'R&M (Inhouse)', FALSE),
('6142', 'R&M (Out)', FALSE),
('7010', 'CapEx - Unit Turns', TRUE),
('7020', 'CapEx - Structural', TRUE),
('7030', 'CapEx - Exterior & Roofing', TRUE),
('7035', 'CapEx - Land Planning', TRUE),
('7050', 'CapEx - Other', TRUE),
('6193', 'Admin Setup', TRUE),
('6141', 'R&M Labor Hours Bill Back', TRUE),
('7035', 'CapEx - Landplanning', TRUE),
('7040', 'CapEx - Landscaping', TRUE),
('6119', 'Leasing: Violations', TRUE),
('7010', 'Leasing: Applications', TRUE);


INSERT INTO Employee (Name, Email) VALUES
('Jay Taylor', 'jay@westernslopepm.com'),
('Jonathan Balding', 'jnbalding518@icloud.com'),
('Kat Barker', 'kat@westernslopepm.com');
